Fix out-of-bounds errors by adding boundary checks for outlines and annotations
This solved my issue from #46 with the "Could not get zip - 7n1;
Error: `index` must be at least 0 and at most 363, but was actually 369" error.

The issue was caused by the eBook's metadata file (uma.json) referencing page numbers that do not exist in the decrypted PDF file resulting in a mismatch (the script attempted to access 369 pages although the eBook only has 364)